### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by FransBillqvist** [FransBillqvist/SnusULoose#11]
UserId
SnuffId
AmountSaved
SavingsPerWeek
SavingsPerMonth
SavingsPerYear
---------------
Redo

**Comment by FransBillqvist** [comment]
kommer väl behöva vara båda då datan skicka så ska det vara en dto

**Comment by Zaai90** [comment]
> kommer väl behöva vara båda då datan skicka så ska det vara en dto

Precis, tänker att en entity enbart är basobjektet. Dto kan du samla ihop/göra uträkningar osv från entiteterna och skicka in i dtot.
