### ISSUE TITLE
DB or Not

### ISSUE THREAD

**Issue by FransBillqvist** [FransBillqvist/SnusULoose#3]
ska vi använda oss utav en databas?

Alts
SQL
Mongo
Cosmos

Pros
Bra med att träna på att sätta upp egen DB och kunna hosta appen

Cons
kan kosta pengar, kan ta tid att få bra struktur på

**Comment by DTSD21** [comment]
Tycker vi kan återvända till Mongo så att vi kommer in i det igen! Borde gå relativt smärtfritt att hosta en liten db i utvecklingssyfte.

**Comment by FransBillqvist** [comment]
2 av 2 röster på Mongo, Projektet avser då att Mongo ska vara vår DB
