### ISSUE TITLE
User class

### ISSUE THREAD

**Issue by FransBillqvist** [FransBillqvist/SnusULoose#4]
Vad ska User klassen innehålla

1. Id
2. FirstName
3. senare mail/password mm.
4. StartDate(?)
//kan byggas ut med tiden frågan är om man ska hålla all info om snusande/slutandet i en egen klass? Just därför startdate kanske inte ska ligga här

**Comment by DTSD21** [comment]
Förslag på ytterligare properties:
Snussort?
Sort av mål? (sluta helt eller gå ner i antal prillor?)
Variabler för hur mycket pengar en användare sparat, hur mycket hen sparar per dag/vecka/månad/år?

**Comment by FransBillqvist** [comment]
User: 
ID
Email
Password
Firstname
Lastname
---------
Redo att skapas
