### ISSUE TITLE
Kolla med Erik hur man fixar så att kort skapas när man gör nya issues!

### ISSUE THREAD

**Issue by DTSD21** [FransBillqvist/SnusULoose#5]
Hotta upp vår github workflow med lite experthjälp!

**Comment by FransBillqvist** [comment]
fixed?

**Comment by FransBillqvist** [comment]
Du går på projects på höger sidan väljer Develop sen kommer kortet skapas AutoMagiskt

**Comment by DTSD21** [comment]
Magi™
