### ISSUE TITLE
Miro med flödesschema

### ISSUE THREAD

**Issue by DTSD21** [FransBillqvist/SnusULoose#6]
Sätt upp en miro med en variant av ett flödesschema på hur appen är tänkt att fungera när den startas.

**Comment by DTSD21** [comment]
https://miro.com/app/board/uXjVO-cFpQ8=/

**Comment by FransBillqvist** [comment]
https://www.figma.com/team_invite/redeem/m4NL738LQSI9d8ukAvoFBq

**Comment by FransBillqvist** [comment]
Vi har nu gjort en start och registerings  sida i figma!
